/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package geodetic;

/**
 *
 * @author wilsonrm
 */
public class geodeticGUI extends javax.swing.JFrame {

    /**
     * Creates new form geodeticGUI
     */
    public geodeticGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lat1 = new javax.swing.JTextField();
        lat1Label = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        lon1Label = new javax.swing.JLabel();
        lon1 = new javax.swing.JTextField();
        lat2Label = new javax.swing.JLabel();
        lat2 = new javax.swing.JTextField();
        lon2Label = new javax.swing.JLabel();
        lon2 = new javax.swing.JTextField();
        distance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PFRR Geodetic Calculator");

        lat1.setText("latitude 1");

        lat1Label.setText("Lat  1");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        lon1Label.setText("Lon 1");

        lon1.setText("longitude 1");

        lat2Label.setText("Lat  2");

        lat2.setText("latitude 2");

        lon2Label.setText("Lon 2");

        lon2.setText("longitude 2");
        lon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lon2ActionPerformed(evt);
            }
        });

        distance.setText("distance");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(calculateButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(distance))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(lon1Label)
                                .add(18, 18, 18)
                                .add(lon1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lat2Label)
                                .add(18, 18, 18)
                                .add(lat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lon2Label)
                                .add(18, 18, 18)
                                .add(lon2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lat1Label)
                                .add(18, 18, 18)
                                .add(lat1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 201, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {lat1Label, lat2Label, lon1Label, lon2Label}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {lat1, lat2, lon1, lon2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lat1Label)
                    .add(lat1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lon1Label)
                    .add(lon1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lat2Label)
                    .add(lat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lon2Label)
                    .add(lon2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(calculateButton)
                    .add(distance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // based on the haversine formula
        // http://rosettacode.org/wiki/Haversine_formula#Java
        double R = 6372.8; // In kilometers
        
        double myLat1;
        double myLon1;
        double myLat2;
        double myLon2;
        float myDistance;
        
        myLat1 = (double)(Double.parseDouble(lat1.getText()));
        myLon1 = (double)(Double.parseDouble(lon1.getText()));
        myLat2 = (double)(Double.parseDouble(lat2.getText()));
        myLon2 = (double)(Double.parseDouble(lon2.getText()));
        
        double dLat = Math.toRadians(myLat1 - myLat1);
        double dLon = Math.toRadians(myLon2 - myLon1);
        myLat1 = Math.toRadians(myLat1);
        myLat2 = Math.toRadians(myLat2);
 
        double a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.sin(dLon / 2) * Math.sin(dLon / 2) * Math.cos(myLat1) * Math.cos(myLat2);
        double c = 2 * Math.asin(Math.sqrt(a));
        
        myDistance = (float)(R*c);
        
        distance.setText(myDistance + " km");
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void lon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(geodeticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(geodeticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(geodeticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(geodeticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new geodeticGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField distance;
    private javax.swing.JTextField lat1;
    private javax.swing.JLabel lat1Label;
    private javax.swing.JTextField lat2;
    private javax.swing.JLabel lat2Label;
    private javax.swing.JTextField lon1;
    private javax.swing.JLabel lon1Label;
    private javax.swing.JTextField lon2;
    private javax.swing.JLabel lon2Label;
    // End of variables declaration//GEN-END:variables
}
